[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
build_flags =
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  vintlabs/fauxmoESP @ ^3.4.1
