[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600
board_build.flash_mode = dio
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  vintlabs/fauxmoESP @ ^3.4.1
